### ISSUE TITLE
Crash beim nutzen des Diagnosegeräts 

### ISSUE THREAD

**Issue by thumbsucker** [mexyn/statev_v2_issues#1987]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Riley Everett

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.11.2021 - 22:35 Uhr

**Beobachtetes Verhalten**
Beim Versuch nach einer Service-Leistung einen erneuten Check durchzuführen, habe ich folgende Fehlermeldung erhalten: 

Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at CarScannerComponent (http://resource/client/ui/index.js:1379944:38)
    at renderWithHooks (http://resource/client/ui/index.js:12730:28)
    at updateFunctionComponent (http://resource/client/ui/index.js:14555:30)
    at beginWork (http://resource/client/ui/index.js:15647:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)

**Erwartetes Verhalten**
Ich habe das Gerät vermutlich etwas zu schnell nutzen wollen, jedoch sollte der Fehler denke ich dennoch nicht auftreten. 

**Optional: Video / Bilder des Fehlers**
![Grand_Theft_Auto_V_Screenshot_2021 11 01_-_22 35 15 45](https://user-images.githubusercontent.com/74800184/139748316-82db71a4-bb53-4818-a9b4-4d1fc0c4b5f2.png)

**Comment by Hutstaender** [comment]
Ist das Problem seither nochmal aufgetreten?

**Comment by thumbsucker** [comment]
Bisher nicht mehr, nein

**Comment by Hutstaender** [comment]
Bitte erneut öffnen, sobald es nochmal auftritt. Sollte aber nicht mehr so sein.
