### ISSUE TITLE
Userinterface abgestürzt

### ISSUE THREAD

**Issue by wichtTSV** [mexyn/statev_v2_issues#1995]
**Character Name**
Tom Spider

**Auftrittszeitpunkt (Datum / Uhrzeit)**
3.11.2021 12:00 Uhr

**Beobachtetes Verhalten**
Fehlermeldung beim öffnen des Interfaces der Gießerei

**Erwartetes Verhalten**
Das die Fehlermeldung nicht kommt.

**Schritte um den Fehler nachvollziehen zu können**
Userinterface der Gießerei öffnen, ist allerdings jetzt das erste mal passiert.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
SellFactory(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Error: SellFactory(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers2 (http://resource/client/ui/index.js:12184:31)
    at reconcileChildren (http://resource/client/ui/index.js:14329:39)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:14902:15)
    at beginWork (http://resource/client/ui/index.js:15637:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)

![image](https://user-images.githubusercontent.com/74994115/140049284-3be5c351-2e30-40d1-bd8a-8ee31887d7d5.png)

**Comment by Hutstaender** [comment]
fixed next update
