### ISSUE TITLE
UI Fehler beim ATM 

### ISSUE THREAD

**Issue by endlessrider273** [mexyn/statev_v2_issues#2033]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jan_Behrend

14.11.2021, 14.45-14.50

Bin an den ATM gegeangen und bekamm einen Fehler über den Bildschirm Angezeigt.

Wollte nur Geld abheben 

Zum ATM; E Drücken = Tadaa, da kam der Fehler

1080p, 60Hz

Fehlercode:
SellFactory(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Error: SellFactory(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers2 (http://resource/client/ui/index.js:12184:31)
    at reconcileChildren (http://resource/client/ui/index.js:14329:39)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:14902:15)
    at beginWork (http://resource/client/ui/index.js:15637:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)

**Comment by DrGrizzlY17** [comment]
#2010
