### ISSUE TITLE
Finger zeigen (B) funktioniert immer mal wieder nicht

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2036]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
schon immer (seit V2) ?

**Beobachtetes Verhalten**
Es kommt immer mal wieder random vor, dass man nicht mehr mit B zeigen kann. Es passiert dann einfach nix.

**Schritte um den Fehler nachvollziehen zu können**
Ich schau mal, ob ich das die Tage reproduzieren kann, aber bisher noch nicht rausgefunden woran es liegt. Ich hab aber das Gefühl, dass es zur Zeit häufiger vorkommt als früher.

**Comment by JohnRappStateV** [comment]
Workaround: Kurz Handy rausholen, dann gehts wieder. So mach ich das zumindest

**Comment by JannikDatsch** [comment]
Gut zu wissen

**Comment by its4l3x** [comment]
Fixed

**Comment by Beartox** [comment]
Davis Markt genauso auch die gleiche Fehlermeldung habe es jedes Mal mehrfach getestet aber jedes Mal die gleiche Fehlermeldung

`A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19)
    at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22)
    at runWithPriority$1 (http://resource/client/ui/index.js:10137:20)
    at flushPassiveEffects (http://resource/client/ui/index.js:18392:24)
    at http://resource/client/ui/index.js:18311:21
    at workLoop (http://resource/client/ui/index.js:1976:44)
    at flushWork (http://resource/client/ui/index.js:1955:24)
    at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)`
