### ISSUE TITLE
2x UseInterface abgestürtzt nach Update beim Marktplatz

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#2061]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jens Reitz

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19:20

**Beobachtetes Verhalten**
A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19)
    at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22)
    at runWithPriority$1 (http://resource/client/ui/index.js:10137:20)
    at flushPassiveEffects (http://resource/client/ui/index.js:18392:24)
    at http://resource/client/ui/index.js:18311:21
    at workLoop (http://resource/client/ui/index.js:1976:44)
    at flushWork (http://resource/client/ui/index.js:1955:24)
    at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)

**Erwartetes Verhalten**

Marktplatz sollte aufgehen

**Schritte um den Fehler nachvollziehen zu können**
An MArktplatz gehen und öffnen  und abstürtzten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Dean-Gallagher** [comment]
jup bei mir auch A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19)
    at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22)
    at runWithPriority$1 (http://resource/client/ui/index.js:10137:20)
    at flushPassiveEffects (http://resource/client/ui/index.js:18392:24)
    at http://resource/client/ui/index.js:18311:21
    at workLoop (http://resource/client/ui/index.js:1976:44)
    at flushWork (http://resource/client/ui/index.js:1955:24)
    at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)

**Comment by its4l3x** [comment]
fixed next update
