### ISSUE TITLE
Crash game error

### ISSUE THREAD

**Issue by Chiko-Garcia** [mexyn/statev_v2_issues#2063]
Chiko Garcia

am markt platz PLZ: 4015
19:30 uhr
nicht nur ein mal bei jedes mal wenn du mit dem markler reden willst

[https://gyazo.com/b2b4644d26447c4fb1ce7d30b8b83c0d](url)

A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19)
    at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22)
    at runWithPriority$1 (http://resource/client/ui/index.js:10137:20)
    at flushPassiveEffects (http://resource/client/ui/index.js:18392:24)
    at http://resource/client/ui/index.js:18311:21
    at workLoop (http://resource/client/ui/index.js:1976:44)
    at flushWork (http://resource/client/ui/index.js:1955:24)
    at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)

**Comment by its4l3x** [comment]
fixed next update
