### ISSUE TITLE
Gamecrash am Marktplatz Sägewerk Paleto

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#2064]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.11.2021 / 19:44 Uhr

**Beobachtetes Verhalten**
Beim Ansprechen des Marktplatz-NPC in Paleto Sägewerk folgender Error:

A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19)
    at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22)
    at runWithPriority$1 (http://resource/client/ui/index.js:10137:20)
    at flushPassiveEffects (http://resource/client/ui/index.js:18392:24)
    at http://resource/client/ui/index.js:18311:21
    at workLoop (http://resource/client/ui/index.js:1976:44)
    at flushWork (http://resource/client/ui/index.js:1955:24)
    at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)

**Comment by 48619** [comment]
Marktplatz Richman

`A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19)
    at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22)
    at runWithPriority$1 (http://resource/client/ui/index.js:10137:20)
    at flushPassiveEffects (http://resource/client/ui/index.js:18392:24)
    at http://resource/client/ui/index.js:18311:21
    at workLoop (http://resource/client/ui/index.js:1976:44)
    at flushWork (http://resource/client/ui/index.js:1955:24)
    at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)`

**Comment by miischaa** [comment]
Der Crash kommt an jedem erdenklichen Marktplatz, zumindest in Sandy Shore und unten an der großen Mall in der Southside, auch bei unterschiedlichen Personen.

**Comment by its4l3x** [comment]
fixed next update
