### ISSUE TITLE
Diagnosegerät

### ISSUE THREAD

**Issue by Oger8602** [mexyn/statev_v2_issues#2065]
**Otto_Gust**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.11.2021/20:19

**Beobachtetes Verhalten**
Diagnosegerät öffnet sich zum Teil gar nicht oder bleibt beim Scannen hängen. Teilweise funktioniert es wie immer.

**Erwartetes Verhalten**
Sollte wie gewohnt immer Funktionieren.

**Schritte um den Fehler nachvollziehen zu können**
Diagnosegerät benutzen.

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/74772342/143623234-8225f696-20dc-45f6-8903-e757c7def9d9.png)

**Comment by its4l3x** [comment]
@TeubyDE @TheOutburst 

Könnt ihr mir das bitte confirmen?

**Comment by TeubyDE** [comment]
`[22:11:57][Error] Attachments Error: Unknown Attachment Used: WDSP_GADGET_PARACHUTE
[22:11:58] blip hidden  Blip{ name: Hotelzimmer, category: 255 } 255
[22:11:58] blip hidden  Blip{ name: Hotelzimmer, category: 255 } 255
[22:11:58][Error] [WEB, View 000001AAC5F977C0] http://resource/client/ui/index.js:258:Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s 

Check the render method of `MainUi`.  
    at div
    at MainUi (http://resource/client/ui/index.js:1362302:26)
    at ErrorBoundary (http://resource/client/ui/index.js:1421395:7)
    at div
    at App (http://resource/client/ui/index.js:1421428:20)
[22:11:58] Connecting to WebSocket...
[22:11:59] Connecting to WebSocket!
[22:11:59] Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[22:11:59] Connecting to WebSocket!
[22:12:00] null
[22:12:00][Error] [WEB] (View 000001AAC5F977C0) Could not load http://78.47.167.120:4300/#/lspd/main/dashboard (ERR_CONNECTION_REFUSED)
[22:12:02] WebSocket connection closed
[22:12:03][Error] [WEB, View 000001AAC5F977C0] http://resource/client/ui/index.js:258:Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s 

Check the render method of `SkillOverview`.  
    at RedLineSpacer (http://resource/client/ui/index.js:1391505:26)
    at SkillOverview (http://resource/client/ui/index.js:1391535:26)
    at div
    at div
    at div
    at div
    at SkilltreeComponent (http://resource/client/ui/index.js:1391623:70)
    at ErrorBoundary (http://resource/client/ui/index.js:1421395:7)
    at div
    at App (http://resource/client/ui/index.js:1421428:20)
[22:12:05][Error] [WEB, View 000001AAC5F977C0] http://resource/client/ui/index.js:258:Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s 

Check the render method of `SkillDetailsPanel`.  
    at tr
    at SkillDetailsPanel (http://resource/client/ui/index.js:1391286:30)
    at SkillPanel (http://resource/client/ui/index.js:1391401:23)
    at div
    at div
    at div
    at SkillOverview (http://resource/client/ui/index.js:1391535:26)
    at div
    at div
    at div
    at div
    at SkilltreeComponent (http://resource/client/ui/index.js:1391623:70)
    at ErrorBoundary (http://resource/client/ui/index.js:1421395:7)
    at div
    at App (http://resource/client/ui/index.js:1421428:20)`

**Comment by Hutstaender** [comment]
Tritt das nach den Fixes noch auf?
