### ISSUE TITLE
Werkstattkasse stellt keine Rechnung aus

### ISSUE THREAD

**Issue by Summ-IT** [mexyn/statev_v2_issues#2103]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**John_Winston**

**seit 02.12.2021**

**WerkstattKasse stellt einem selber keine Rechnungen aus. Man bekommt zwar einen Mauszeiger aber nichts zu unterschreiben. Muss jedes mal neu auf den Server kommen damit ich wieder an die Kasse komme und dann ist aber wieder das gleiche Problem**

**Rechnung austellen**

**Schritte um den Fehler nachvollziehen zu können**

**1920x1080**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
Konnte das nicht genau 1 zu 1 nachstellen. Jedoch taucht folgender Error auf:
`[21:37:00][Error] [WEB, View 000001BC42E2CDA0] http://resource/client/ui/index.js:258:Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s 

Check the render method of `MechanicBuyComponent`.  
    at tr
    at MechanicBuyComponent (http://resource/client/ui/index.js:1379899:33)
    at div
    at MechanicComponent (http://resource/client/ui/index.js:1387363:61)
    at ErrorBoundary (http://resource/client/ui/index.js:1442735:7)
    at div
    at App (http://resource/client/ui/index.js:1442768:20)
[21:37:00][Error] [WEB, View 000001BC42E2CDA0] http://resource/client/ui/index.js:2500:Warning: validateDOMNesting(...): %s cannot appear as a child of <%s>.%s%s%s <tr> table   Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser. 
    at tr
    at table
    at div
    at div
    at div
    at div
    at MechanicBuyComponent (http://resource/client/ui/index.js:1379899:33)
    at div
    at MechanicComponent (http://resource/client/ui/index.js:1387363:61)
    at ErrorBoundary (http://resource/client/ui/index.js:1442735:7)
    at div
    at App (http://resource/client/ui/index.js:1442768:20)`

**Comment by Summ-IT** [comment]
Schau mal ob du die mthode mit der richtigen klasse auch verbunden hastVon meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Lukas T ***@***.***>Datum: So., 5. Dez. 2021, 21:41An: mexyn/statev_v2_issues ***@***.***>Cc: Summ-IT ***@***.***>, Author ***@***.***>Betreff: Re: [mexyn/statev_v2_issues] Werkstattkasse stellt keine Rechnung aus (Issue #2103)
Konnte das nicht genau 1 zu 1 nachstellen. Jedoch taucht folgender Error auf:
`[21:37:00][Error] [WEB, View 000001BC42E2CDA0] http://resource/client/ui/index.js:258:Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s
Check the render method of MechanicBuyComponent.
at tr
at MechanicBuyComponent (http://resource/client/ui/index.js:1379899:33)
at div
at MechanicComponent (http://resource/client/ui/index.js:1387363:61)
at ErrorBoundary (http://resource/client/ui/index.js:1442735:7)
at div
at App (http://resource/client/ui/index.js:1442768:20)
[21:37:00][Error] [WEB, View 000001BC42E2CDA0] http://resource/client/ui/index.js:2500:Warning: validateDOMNesting(...): %s cannot appear as a child of <%s>.%s%s%s  table   Add a ,  or  to your code to match the DOM tree generated by the browser.
at tr
at table
at div
at div
at div
at div
at MechanicBuyComponent (http://resource/client/ui/index.js:1379899:33)
at div
at MechanicComponent (http://resource/client/ui/index.js:1387363:61)
at ErrorBoundary (http://resource/client/ui/index.js:1442735:7)
at div
at App (http://resource/client/ui/index.js:1442768:20)`
