### ISSUE TITLE
UI beim ATM Knacken abestürzt

### ISSUE THREAD

**Issue by RIT-FR** [mexyn/statev_v2_issues#2168]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Tony_Herrera

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.12.2021 04:01

**Beobachtetes Verhalten**
UI Abgestürzt

**Schritte um den Fehler nachvollziehen zu können**
ATM Knacken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Error: SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers2 (http://resource/client/ui/index.js:12184:31)
    at reconcileChildren (http://resource/client/ui/index.js:14329:39)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:14902:15)
    at beginWork (http://resource/client/ui/index.js:15637:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)
    
    
![Screenshot_28](https://user-images.githubusercontent.com/77400784/147800625-a81e187e-99c2-4115-bf6d-556cf986c1ba.png)

**Comment by Hutstaender** [comment]
#2144
