### ISSUE TITLE
UI Crash Geldautomat 

### ISSUE THREAD

**Issue by JosefRitter** [mexyn/statev_v2_issues#2271]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Josef Ritter**

**09.02 um 13:50 Uhr **

**UI Crash Geldautomat**

**gegenüber von alten Lioncut**

**SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Error: SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers2 (http://resource/client/ui/index.js:12184:31)
    at reconcileChildren (http://resource/client/ui/index.js:14329:39)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:14902:15)
    at beginWork (http://resource/client/ui/index.js:15637:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)**

**Comment by RealSocius** [comment]
![image](https://user-images.githubusercontent.com/43414545/153776699-29002c53-b9e0-4cbd-b34b-37f535fb028c.png)

Passiert hier ebenfalls. Wahrscheinlich, weil die UI vom Automaten und vom Gebäude gleichzeitig geladen werden.

**Comment by Enemyaa** [comment]
Danke! Next Update!
