### ISSUE TITLE
Fehlercode beim öffnen vom Telefonverlauf

### ISSUE THREAD

**Issue by Pregon** [mexyn/statev_v2_issues#2363]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.04.2022 12:40

**Beobachtetes Verhalten**
Fehlercode beim öffnen vom Telefonverlauf

Cannot read property 'find' of null
TypeError: Cannot read property 'find' of null
    at getcallItemSize (http://resource/client/ui/index.js:1417523:35)
    at http://resource/client/ui/index.js:1417565:80
    at Array.map (<anonymous>)
    at Callinglist (http://resource/client/ui/index.js:1417563:51)
    at renderWithHooks (http://resource/client/ui/index.js:12730:28)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:14850:23)
    at beginWork (http://resource/client/ui/index.js:15637:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)

**Erwartetes Verhalten**
Keinen Fehlercode und Telefonverlauf öffnet sich

**Comment by its4l3x** [comment]
@Notiz

Eine Sicherheitsabfrage 'alla ob das Array existent ist o.Ä. sollte gemacht werden bevor ein .find() aufgerufen wird.
Am besten Array.isArray() oder checken ob null ist, dann ein default value returnen.
