### ISSUE TITLE
UI Crash

### ISSUE THREAD

**Issue by SatyriaDine** [mexyn/statev_v2_issues#2400]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.04.2022 gegen 12:30Uhr

**Beobachtetes Verhalten**
UI Crash durch E Drücken am Geldautomaten 

Crash-Bericht: 

SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Error: SetInterior(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers2 (http://resource/client/ui/index.js:12184:31)
    at reconcileChildren (http://resource/client/ui/index.js:14329:39)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:14902:15)
    at beginWork (http://resource/client/ui/index.js:15637:24)
    at HTMLUnknownElement.callCallback2 (http://resource/client/ui/index.js:5340:24)
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5365:26)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at beginWork$1 (http://resource/client/ui/index.js:18746:17)
    at performUnitOfWork (http://resource/client/ui/index.js:17977:22)
    at workLoopSync (http://resource/client/ui/index.js:17928:15)

**Comment by SatyriaDine** [comment]
Mirrowpark gegenüber vom Fawkes Friseursalon wo die Firmen sind. Der Geldautomat der näher an dem dort auch befindlichen Mülleimer ist.

**Comment by DrGrizzlY17** [comment]
Ist daneben nen Marker für ne Firma oder Haus der nah am Bankautomat ist? Am besten mal Marker an machen

**Comment by SatyriaDine** [comment]
ja direkt daneben ist ein Firmenmarker. Der auch immer getriggered wird wenn man an den Automaten geht. Marker hab ich aber auch immer an.

**Comment by SatyriaDine** [comment]
Macht sinn. Ist mir schon bei einigen Automaten passiert. Heute zum ersten Mal mit UI Crash :D

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2424
