### ISSUE TITLE
Perso wird nicht angezeigt, sondern Fehlermeldung

### ISSUE THREAD

**Issue by Schamocke** [mexyn/statev_v2_issues#3010]
Folgender Code wird beim persönlichen Anzeigen des Ausweises angezeigt und man muss danach re-connecten.

Cannot read properties of undefined (reading 'label')
TypeError: Cannot read properties of undefined (reading 'label')
    at http://resource/client/ui/index.js:1313016:1089
    at Array.map (<anonymous>)
    at IdentificationPaperComponent (http://resource/client/ui/index.js:1312975:20)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at updateFunctionComponent (http://resource/client/ui/index.js:15974:30)
    at beginWork (http://resource/client/ui/index.js:17280:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)

**Comment by simplycach** [comment]
Hast du zufällig nen Video davon bzw. tritt der Fehler öfter auf ?

**Comment by Schamocke** [comment]
Ein Video hab ich nicht. Komme heute auch leider nicht mehr dazu. Aber der Fehler tritt immer auf, wenn ich den Perso übers Inventar öffnen will.

**Comment by MarkHarland** [comment]
@CrazyKee Ich denke mal es liegt wieder an der Augenfarbe  schaust du dir das mal an ?

**Comment by CrazyKee** [comment]
@Schamocke Hallo. Konnte das Problem bereits behoben werden? Ansonsten würde ich dich bitten ein Ticket auf dem Discord zu erstellen.
