### ISSUE TITLE
UI Crash nach UI Fehler

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3097]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

20:01
**Beobachtetes Verhalten**

Nachdem das Inventar falsch angezeigt wird, ist das UI gecrashed

Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at ItemList (http://resource/client/ui/index.js:1304236:110)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:16315:23)
    at beginWork (http://resource/client/ui/index.js:17270:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performSyncWorkOnRoot (http://resource/client/ui/index.js:20198:30)

**Erwartetes Verhalten**

Ohne Crash
**Schritte um den Fehler nachvollziehen zu können**

Kaputtes Inventar haben
Portmonee öffnen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SternChef** [comment]
Petra_Tallons
Zeitpunkt: 26.02.24 ca. 05:45 Uhr

Inventar wurde leer angezeigt; dann crash der UI

Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at ItemList (http://resource/client/ui/index.js:1304236:110)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:16315:23)
    at beginWork (http://resource/client/ui/index.js:17270:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performSyncWorkOnRoot (http://resource/client/ui/index.js:20198:30)

**Comment by Toby-cmd** [comment]
![Screenshot 2024-02-27 103006](https://github.com/eiksch/statev_v3_issues/assets/69426336/1a8db51a-77fb-4c69-817f-893fe74c38e8)

**Comment by simplycach** [comment]
Bereits offen https://github.com/eiksch/statev_v3_issues/issues/3063
