### ISSUE TITLE
Inventar Bug

### ISSUE THREAD

**Issue by LeonF0207** [mexyn/statev_v2_issues#3106]
**Character Name**
Jake Thompson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.02.24 zwischen 4:00 u. 4:30

**Beobachtetes Verhalten**
Ich wollte im Hotelzimmer auf den normalen Schrank unterm Fernseher zu greifen und als ich das Inventar geschlossen habe hing ich hinterm Fernseher fest und darauf hin habe ich mich ausgeloggt und wieder eingeloggt, war somit wieder frei aber als ich mein Inventar geöffnet habe, wurde nichts was ich im Inventar hatte angezeigt sowie mein Bargeld ebenso nicht und statt des Bargeldes stand dort "######".

**Erwartetes Verhalten**
Inventar sollte eigentlich normal angezeigt werden sowie das Bargeld.

**Schritte um den Fehler nachvollziehen zu können**
Ich habe keine Ahnung, ob das damit zusammen hängt oder einfach Random passiert ist.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Fehlercode**
Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at ItemList (http://resource/client/ui/index.js:1313345:110)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:16315:23)
    at beginWork (http://resource/client/ui/index.js:17270:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performSyncWorkOnRoot (http://resource/client/ui/index.js:20198:30)

**Comment by simplycach** [comment]
Bereits offen https://github.com/eiksch/statev_v3_issues/issues/3063
