### ISSUE TITLE
AutoLeasing 6026

### ISSUE THREAD

**Issue by chameleon47** [mexyn/statev_v2_issues#3117]
Das kommt jedes mal, wenn ich mit dem Leasing NPC interagiere.

Fehlermeldung:
Cannot read properties of null (reading 'label')
TypeError: Cannot read properties of null (reading 'label')
    at LeasingSelectComponent (http://resource/client/ui/index.js:1590706:21)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:16315:23)
    at beginWork (http://resource/client/ui/index.js:17270:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performConcurrentWorkOnRoot (http://resource/client/ui/index.js:20004:32)

![Bild_2024-03-02_061912827](https://github.com/eiksch/statev_v3_issues/assets/161916408/b8113a9b-43c5-43aa-9359-ab7662ce208a)

**Comment by chameleon47** [comment]
restart hilft nicht, das Fenster ist dann natürlich geschlossen, aber kommt jedes mal

**Comment by DrGrizzlY17** [comment]
gibt dafür bereits eine ankündigung auf dem discord das der NPC aktuell nicht funktioniert

**Comment by chameleon47** [comment]
> gibt dafür bereits eine ankündigung auf dem discord das der NPC aktuell nicht funktioniert

achso danke
