### ISSUE TITLE
Bugreport Inventar

### ISSUE THREAD

**Issue by chameleon47** [mexyn/statev_v2_issues#3132]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jack Gusto**

**04.03.24 15:30**

**Inventar mit I geöffnet, dann habe ich gemerkt, dass mein Inventar "weg" ist, also keine Items vorhanden und oben 0 von 1kg stand. (Sollte ja eigentlich 15 sein.**

**meine Spitzhacke hätte drin sein sollen**

**Iventar mit I öffnen**

**nicht sicher ob das als UI/Displayfehler zählt, wenn schon dann 1920x1080p**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/161916408/ea706e47-0859-452a-b2d0-b1e5c6a6b66f)

**Comment by chameleon47** [comment]
Hier das blau markierte als Text:

Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at ItemList (http://resource/client/ui/index.js:1314350:110)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at mountIndeterminateComponent (http://resource/client/ui/index.js:16315:23)
    at beginWork (http://resource/client/ui/index.js:17270:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performSyncWorkOnRoot (http://resource/client/ui/index.js:20198:30)

**Comment by chameleon47** [comment]
Neustart hat es gefixt, kann auch ganz normal weiter minen

**Comment by simplycach** [comment]
Ist bekannt.
