### ISSUE TITLE
Inventar / Interaktionsfehler

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3145]
**Jayden_Banks**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
07.03.2024 12:16:42

**Beobachtetes Verhalten**
Inventar leer, keine interaktion mit schränken möglich

**Optional: Video / Bilder des Fehlers**
altv log fehler:
[12:16:42][Error] [WEB, View 00000000D907AD20] http://resource/client/ui/index.js:150:Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s 

Check the render method of `ItemList`.  
    at div
    at ItemList (http://resource/client/ui/index.js:1314390:21)
    at div
    at div
    at div
    at div
    at div
    at div
    at ClothingInventoryComponent (http://resource/client/ui/index.js:1325779:70)
    at ErrorBoundary (http://resource/client/ui/index.js:1593928:7)
    at RecoilRoot_INTERNAL (http://resource/client/ui/index.js:101734:5)
    at RecoilRoot (http://resource/client/ui/index.js:101851:7)
    at div
    at App (http://resource/client/ui/index.js:1594001:20)

**Comment by evanhaugestatev** [comment]
Wir konnten da leider noch nichts reproduzieren. Kannst du uns dein Vorgehen näher beschreiben?

**Comment by FLVFFY1** [comment]
leider nein, hatte mich eingeloggt, meine klamotten ausgezogen und dann mit E den kleiderschrank geöffnet und da war schon alles leer. dann relogg und die ausgezogenen sachen waren weg, schrank und inventar aber wieder gefüllt

**Comment by TheOutburst** [comment]
sollte mit dem Update heute nichtmehr vorkommen, ich vermute das hier war ein Folgefehler
