### ISSUE TITLE
Crash UserInterface

### ISSUE THREAD

**Issue by Mondmadchen** [mexyn/statev_v2_issues#3446]
**Camille_Duvall**

**30.05.2024, 18.06**

**Beobachtetes Verhalten**
Ich befand mich am Hafen, am Startpunkt des Auslieferungs-Jobs. Ich habe mich ungefähr 10 Minuten in der Rauchen-Animation befunden. Beim Versuch das X-Menü zu öffnen stürzte das UserInterface ab.

**Erwartetes Verhalten**
Interface stürzt nicht ab.

**Schritte um den Fehler nachvollziehen zu können**
Ist bisher bei mir noch nicht aufgetreten.

**Optional: Video / Bilder des Fehlers**
![Bild_2024-05-30_180849026](https://github.com/eiksch/statev_v3_issues/assets/95969070/3be752e9-d181-49d3-8998-d1ca7b87c034)

Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at XMenuComponent (http://resource/client/ui/index.js:1149598:204)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at updateFunctionComponent (http://resource/client/ui/index.js:15974:30)
    at beginWork (http://resource/client/ui/index.js:17280:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performConcurrentWorkOnRoot (http://resource/client/ui/index.js:20004:32)

**Comment by rodistic** [comment]
next update fixed
