### ISSUE TITLE
UserInterface ist abgestürzt bei Wohnung

### ISSUE THREAD

**Issue by CurveOG** [mexyn/statev_v2_issues#3569]
**Character Name**
Darnell Davis

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.07.2024 um 15:00

**Beobachtetes Verhalten**
Kann meine Wohnung nicht betreten, weil anstatt des Hausmenüs zum eintreten der Wohnung, eine Fehlermeldung kommt.

**Erwartetes Verhalten**
Option zum betreten der Wohnung sollte gegeben sein.

**Schritte um den Fehler nachvollziehen zu können**
Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at BuilidingCellMenu (http://resource/client/ui/index.js:1175053:1928)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at updateFunctionComponent (http://resource/client/ui/index.js:15974:30)
    at beginWork (http://resource/client/ui/index.js:17280:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performConcurrentWorkOnRoot (http://resource/client/ui/index.js:20004:32)

Hash: Vespucci_Flat_2_3

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Ist bereits bekannt.
