### ISSUE TITLE
Apartments fehler beim reingehen

### ISSUE THREAD

**Issue by Kaktusprinz** [mexyn/statev_v2_issues#3583]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** John_Prinz

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.07.2024 um 8:27 Uhr

**Erwartetes Verhalten**
Ich geh zum grünen kreis vor meinen Apartment 20 und geh rein. 

**Schritte um den Fehler nachvollziehen zu können**
In Paletto geht man zu dem Motel. Dann geht man die Treppe rauf und zu seiner Zimmernummer, bei mir ist es die 20 und geht auf eintreten. aber dann stürtzt er ab. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at BuilidingCellMenu (http://resource/client/ui/index.js:1175053:1928)
    at renderWithHooks (http://resource/client/ui/index.js:13586:28)
    at updateFunctionComponent (http://resource/client/ui/index.js:15974:30)
    at beginWork (http://resource/client/ui/index.js:17280:24)
    at beginWork$1 (http://resource/client/ui/index.js:21071:24)
    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)
    at workLoopSync (http://resource/client/ui/index.js:20455:15)
    at renderRootSync (http://resource/client/ui/index.js:20434:17)
    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)
    at performConcurrentWorkOnRoot (http://resource/client/ui/index.js:20004:32)

**Comment by simplycach** [comment]
Bereits bekannt, bitte über den Blauen Marker reingehen.
