### ISSUE TITLE
Caddy umfärben Fehler

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3632]
**Character Name**
Charly Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.08. 19 Uhr

**Beobachtetes Verhalten**
Wenn man den Caddy (11 PS nicht Club) lackieren möchte wirft es folgenden Fehler und blockiert die Hebebühne komplett:

[WEB, View 000000010F301880] http://resource/client/ui/index.js:150:Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s 

Check the render method of `MechanicColorComponent`.  
    at p
    at MechanicColorComponent (http://resource/client/ui/index.js:1195193:5)
    at div
    at MechanicComponent (http://resource/client/ui/index.js:1209287:60)
    at ErrorBoundary (http://resource/client/ui/index.js:1444016:7)
    at RecoilRoot_INTERNAL (http://resource/client/ui/index.js:101601:5)
    at RecoilRoot (http://resource/client/ui/index.js:101718:7)
    at div
    at App (http://resource/client/ui/index.js:1444089:20) 

**Erwartetes Verhalten**
Sollte funktionieren

**Comment by QA-Pregon** [comment]
geht schon um den hier oder:

![image](https://github.com/user-attachments/assets/8677db55-9129-4dbb-a535-845f9ab9abc4)

**Comment by rodistic** [comment]
Ayy Gude,

das System wurde umfassend überarbeitet, wenn der Fehler weiter auftritt bitte erneut melden
